name: browser-stack

on:
#  schedule:
#    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 16.x

      - name: Run browser-stack test
        env:
          BROWSER_STACK_USER_NAME: ${{ secrets.BROWSER_STACK_USER_NAME }}
          BROWSER_STACK_ACCESS_KEY: ${{ secrets.BROWSER_STACK_ACCESS_KEY }}
        run: |
          cd test/browser-stack
          npm ci
          npm test
